# ============================================================
# Kubernetes ConfigMap: Cấu hình chung (AN TOÀN ĐỂ PUSH)
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-config
  namespace: default
data:
  # MinIO
  MINIO_ENDPOINT: "100.74.195.110:30900"
  MINIO_BUCKET: "binance"
  MINIO_SECURE: "false"
  
  # PostgreSQL
  JDBC_URL: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/crypto_dw"
  
  # Spark App
  SPARK_APP_NAME: "CryptoDW-ETL-Production"
