# ============================================================
# Kubernetes Secret: Thông tin nhạy cảm
# Cách tạo: kubectl apply -f secret.yaml
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: etl-secrets
  namespace: spark-etl
type: Opaque
stringData:
  # MinIO Keys
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "Bigdata@MinIO2025"
  
  # PostgreSQL Credentials
  JDBC_USER: "dwuser"
  JDBC_PASSWORD: "dwpassword"
